import type { Metadata } from "next";
import "./globals.css";
import { CubeProvider, CubeCanvas } from "@/components/CubeProvider";
import PageSlot from "@/components/PageSlot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CubeProvider>
          <CubeCanvas />
          <PageSlot>{children}</PageSlot>
        </CubeProvider>
      </body>
    </html>
  );
}
